#!/usr/bin/env python3
"""
NSE Multibagger Discovery System — Standalone Pipeline Cleaner
==============================================================
Program Name: clean_pipeline.py

Objective:
Cleans up all output CSV files, generated markdown/PDF reports, log files,
and research artifacts across all 5 stages of the pipeline.

Usage:
  python3 clean_pipeline.py          # Cleans CSVs, reports, and logs
  python3 clean_pipeline.py --all    # Cleans CSVs, reports, logs, AND the research/ directory
"""

import sys
import shutil
import argparse
from pathlib import Path

ROOT_DIR    = Path(__file__).resolve().parent  # smallcap-alpha-engine/
OUTPUTS_DIR = ROOT_DIR / "outputs"

# Files generated in outputs/ across Stages 1 to 5
FILES_IN_OUTPUTS = [
    # Stage 1 Outputs
    "turnaround_shortlist.csv",
    # Stage 2 Outputs & Logs
    "business_momentum_ranked.csv",
    "business_momentum.log",
    # Stage 3 Outputs & Logs
    "stage3_ai_scores.csv",
    "ai_business_intelligence.log",
    # Stage 4 Outputs & Logs
    "final_multibagger_ranking.csv",
    "top_candidates.csv",
    "portfolio_watchlist.csv",
    "final_investment_report.md",
    "final_ranking.log",
    # Stage 5 Outputs & Logs
    "portfolio_plan.csv",
    "portfolio_strategy_report.md",
    "portfolio_strategy.log",
    # Master Pipeline Log
    "master_pipeline.log",
]

# Directories inside outputs/ to remove with --all
DIRS_IN_OUTPUTS = [
    "research",
    "reports",
]


def clean_pipeline(clean_research: bool = False):
    print("=" * 80)
    print(" 🧹 CLEANING NSE MULTIBAGGER PIPELINE ARTIFACTS")
    print("=" * 80)

    removed_files = 0
    for filename in FILES_IN_OUTPUTS:
        filepath = OUTPUTS_DIR / filename
        if filepath.exists():
            try:
                filepath.unlink()
                print(f"  ✔ Removed file: outputs/{filename}")
                removed_files += 1
            except Exception as e:
                print(f"  ❌ Error removing outputs/{filename}: {e}")

    # Remove index.html from root
    html = ROOT_DIR / "index.html"
    if html.exists():
        try:
            html.unlink()
            print("  ✔ Removed file: index.html")
            removed_files += 1
        except Exception as e:
            print(f"  ❌ Error removing index.html: {e}")

    removed_dirs = 0
    if clean_research:
        for dirname in DIRS_IN_OUTPUTS:
            dirpath = OUTPUTS_DIR / dirname
            if dirpath.exists() and dirpath.is_dir():
                try:
                    shutil.rmtree(dirpath)
                    print(f"  ✔ Removed directory: outputs/{dirname}/")
                    removed_dirs += 1
                except Exception as e:
                    print(f"  ❌ Error removing outputs/{dirname}/: {e}")
    else:
        print("\n  ℹ Note: 'outputs/research/' preserved. Use `python3 clean_pipeline.py --all` to remove research folders.")

    print("\n" + "=" * 80)
    print(f"  ✨ CLEAN COMPLETE: Removed {removed_files} file(s) and {removed_dirs} directory(ies).")
    print("=" * 80 + "\n")


def main():
    parser = argparse.ArgumentParser(
        description="Clean outputs and logs generated by the NSE Multibagger Pipeline"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Also remove the research/ and reports/ directories containing extracted documents",
    )
    args = parser.parse_args()
    clean_pipeline(clean_research=args.all)


if __name__ == "__main__":
    main()
