#!/usr/bin/env python3
"""
NSE Smallcap Multibagger Discovery System — Stage 5: Portfolio & Sell Strategy Engine
======================================================================================
Program Name: 5_portfolio_sell_strategy_engine.py

Objective:
Converts Stage 4 investment rankings (`final_multibagger_ranking.csv`) into actionable
portfolio allocation decisions, risk parameters, and disciplined profit-booking / exit strategies.

Stage 5 Core Functions:
1. Capital Allocation & Position Sizing:
   - Dynamic weight calculation based on Final Score & Conviction Rank.
   - Position allocation % (normalized to 100% portfolio equity).
   - Sample position size calculation for a standard ₹10,00,000 (₹10 Lakh) reference portfolio.
2. Risk & Horizon Management:
   - Buy Priority (High / Medium / Low / Watchlist)
   - Risk Level (Low / Moderate / High)
   - Suggested Holding Period (18-24 Months, 12-18 Months, 6-12 Months)
3. Slab-Wise Profit Booking Framework:
   - Slab 1: Book 20% profit at +25% gain
   - Slab 2: Book 20% profit at +50% gain
   - Slab 3: Book 20% profit at +75% gain
   - Slab 4: Book 20% profit at +100% gain (100% return / Multibagger milestone)
   - Runner: Hold remaining 20% with trailing stop loss to capture extended upside.
4. Exit Strategy & Fundamental Thesis Break Triggers:
   - Initial Hard Stop Loss (e.g., -12.0% from entry price)
   - Trailing Stop Loss (e.g., 15% trailing from peak once gain exceeds +50%)
   - Fundamental Thesis Break Rules (Debt/Equity > 0.50, 2 consecutive negative earnings quarters, promoter selling).

Outputs Generated:
1. portfolio_plan.csv          - Comprehensive portfolio allocation & sell strategy matrix.
2. portfolio_strategy_report.md - Structured executive report detailing portfolio execution rules.
"""

import sys
import logging
import warnings
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Tuple, Any

import pandas as pd
import numpy as np

# Suppress warnings
warnings.filterwarnings("ignore")

# ------------------------------------------------------------------------------
# CONFIGURATION & CONSTANTS
# ------------------------------------------------------------------------------
CONFIG = {
    "REFERENCE_PORTFOLIO_INR": 1000000.0,  # ₹10 Lakhs reference portfolio size
    "HARD_STOP_LOSS_PCT": -12.0,            # Hard stop loss percentage from entry
    "TRAILING_STOP_LOSS_PCT": 15.0,         # Trailing stop loss percentage from peak
    "MAX_SINGLE_STOCK_WEIGHT": 25.0,        # Maximum allocation cap per stock (%)
    "MIN_SINGLE_STOCK_WEIGHT": 5.0,         # Minimum allocation floor per stock (%)
}

BASE_DIR = Path(__file__).resolve().parent.parent / "outputs"  # smallcap-alpha-engine/outputs/
INPUT_RANKING_CSV = BASE_DIR / "final_multibagger_ranking.csv"
OUTPUT_PLAN_CSV = BASE_DIR / "portfolio_plan.csv"
OUTPUT_STRATEGY_MD = BASE_DIR / "portfolio_strategy_report.md"
LOG_FILENAME = BASE_DIR / "portfolio_strategy.log"

# ------------------------------------------------------------------------------
# LOGGING SETUP
# ------------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(str(LOG_FILENAME), mode="w"),
        logging.StreamHandler(sys.stdout),
    ],
)
logger = logging.getLogger("PortfolioSellStrategy")


# ------------------------------------------------------------------------------
# PORTFOLIO ALLOCATION ENGINE
# ------------------------------------------------------------------------------
def load_stage4_rankings() -> pd.DataFrame:
    """Loads final rankings generated by Stage 4."""
    if not INPUT_RANKING_CSV.exists():
        logger.error(f"Input file {INPUT_RANKING_CSV.name} not found. Run Stage 4 first.")
        sys.exit(1)

    df = pd.read_csv(INPUT_RANKING_CSV)
    df.columns = [c.strip() for c in df.columns]
    logger.info(f"Loaded {len(df)} ranked candidates from {INPUT_RANKING_CSV.name}")
    return df


def calculate_portfolio_weights(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes normalized portfolio allocation percentages based on Stage 4 Final Scores.
    Enforces maximum allocation caps and minimum allocation floors.
    """
    df = df.copy()

    # Raw allocation weights proportional to (Final Score - 50)^2 to reward top tier candidates
    scores = df["Final Score"].astype(float)
    raw_weights = np.maximum(scores - 50.0, 5.0) ** 1.5
    total_raw = raw_weights.sum()

    if total_raw > 0:
        alloc_pct = (raw_weights / total_raw) * 100.0
    else:
        alloc_pct = np.full(len(df), 100.0 / len(df))

    # Apply allocation caps & floors
    alloc_pct = np.clip(alloc_pct, CONFIG["MIN_SINGLE_STOCK_WEIGHT"], CONFIG["MAX_SINGLE_STOCK_WEIGHT"])
    # Re-normalize to exactly 100%
    alloc_pct = (alloc_pct / alloc_pct.sum()) * 100.0

    df["Allocation %"] = np.round(alloc_pct, 2)
    df["Position Size (INR)"] = np.round((df["Allocation %"] / 100.0) * CONFIG["REFERENCE_PORTFOLIO_INR"], 2)

    return df


# ------------------------------------------------------------------------------
# STRATEGY & EXIT RULE GENERATOR
# ------------------------------------------------------------------------------
def generate_position_strategy(row: pd.Series) -> Dict[str, Any]:
    """
    Generates risk parameters, buy priority, holding period, slab-wise profit booking,
    and exit/thesis break rules for a single stock position.
    """
    rank = int(row["Rank"])
    score = float(row["Final Score"])
    category = str(row.get("Investment Category", ""))
    classification = str(row.get("Classification", ""))

    # 1. Buy Priority
    if score >= 88.0:
        buy_priority = "P1 - Immediate Core Accumulation"
    elif score >= 80.0:
        buy_priority = "P2 - Tactical Accumulation on Dips"
    elif score >= 72.0:
        buy_priority = "P3 - Secondary Growth Satellite"
    else:
        buy_priority = "P4 - Watchlist Buffer / Staggered Entry"

    # 2. Risk Level
    de_str = str(row.get("Debt/Equity", ""))
    try:
        de_val = float(de_str) if de_str and de_str != "N/A" else 0.3
    except ValueError:
        de_val = 0.3

    if score >= 85.0 and de_val <= 0.25:
        risk_level = "Low Risk (Defensive Compounder)"
    elif score >= 78.0 and de_val <= 0.45:
        risk_level = "Moderate Risk (Growth Capital)"
    else:
        risk_level = "Elevated Risk (High Volatility)"

    # 3. Suggested Holding Period
    if classification == "Emerging Compounder":
        holding_period = "18 – 36 Months (Long-Term Compounding)"
    elif classification == "Cyclical Recovery":
        holding_period = "12 – 24 Months (Capex Cycle Duration)"
    elif classification == "Turnaround Opportunity":
        holding_period = "12 – 18 Months (Earnings Normalization)"
    else:
        holding_period = "6 – 12 Months (Tactical Trade)"

    # 4. Slab-Wise Profit Booking Strategy
    slab_strategy = (
        "Slab 1: 20% at +25% | "
        "Slab 2: 20% at +50% | "
        "Slab 3: 20% at +75% | "
        "Slab 4: 20% at +100% | "
        "Runner: Hold 20% with 15% trailing stop"
    )

    # 5. Exit Strategy & Stop Loss Rules
    hard_stop = f"Hard Stop Loss: -12.0% from avg cost"
    trailing_stop = f"Trailing Stop Loss: 15.0% below peak once gain > +50%"

    # 6. Fundamental Thesis Break Triggers
    thesis_breaks = [
        "Debt-to-Equity ratio exceeds 0.50",
        "Two consecutive quarters of QoQ Net Income decline",
        "Promoter stake reduction > 3.0% in a single quarter",
        "Auditor resignation or major regulatory warning"
    ]
    thesis_break_rules = " ; ".join(thesis_breaks)

    return {
        "Rank": rank,
        "Ticker": row["Ticker"],
        "Final Score": score,
        "Allocation %": row["Allocation %"],
        "Position Size (INR)": row["Position Size (INR)"],
        "Buy Priority": buy_priority,
        "Risk Level": risk_level,
        "Suggested Holding Period": holding_period,
        "Slab-wise Profit Booking": slab_strategy,
        "Stop Loss Rule": f"{hard_stop} | {trailing_stop}",
        "Thesis Break Rules": thesis_break_rules,
        "Investment Category": category,
        "Classification": classification,
        "Investment Thesis": row.get("Investment Thesis", "")
    }


# ------------------------------------------------------------------------------
# REPORT GENERATION MODULE (portfolio_strategy_report.md)
# ------------------------------------------------------------------------------
def generate_portfolio_markdown_report(df_plan: pd.DataFrame) -> Path:
    """Generates executive markdown report: portfolio_strategy_report.md."""
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# NSE Smallcap Multibagger System — Stage 5 Portfolio & Sell Strategy Report",
        f"**Generated Date:** {now_str} | **Reference Portfolio Size:** ₹{CONFIG['REFERENCE_PORTFOLIO_INR']:,.2f} (₹10 Lakhs)",
        "",
        "---",
        "",
        "## Executive Overview",
        "",
        "Stage 5 transforms the final Stage 4 investment rankings into an actionable, disciplined capital allocation plan. "
        "It defines exact position sizing, risk tiers, buy priorities, a 4-tier slab-wise profit booking strategy, "
        "and strict fundamental thesis break rules to maximize returns while managing downside risk.",
        "",
        "---",
        "",
        "## Master Portfolio Allocation & Execution Matrix",
        "",
        "| Rank | Ticker | Final Score | Allocation % | Position Size (₹) | Buy Priority | Risk Level | Suggested Holding Period |",
        "| :---: | :--- | :---: | :---: | :---: | :--- | :--- | :--- |",
    ]

    for _, r in df_plan.iterrows():
        lines.append(
            f"| **#{r['Rank']}** | `{r['Ticker']}` | **{r['Final Score']:.2f}** | "
            f"**{r['Allocation %']:.2f}%** | ₹{r['Position Size (INR)']:,.2f} | "
            f"{r['Buy Priority']} | {r['Risk Level']} | {r['Suggested Holding Period']} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## Slab-Wise Profit Booking & Exit Execution Strategy",
        "",
        "To capture multibagger upside while locking in profits dynamically, all positions follow a structured **5-Slab Exit Framework**:",
        "",
        "```",
        " 📈 +25% Gain  ---> Sell 20% of initial position  (Lock in early gains & reduce risk)",
        " 📈 +50% Gain  ---> Sell 20% of initial position  (De-risk principal capital)",
        " 📈 +75% Gain  ---> Sell 20% of initial position  (Secure substantial profits)",
        " 🚀 +100% Gain ---> Sell 20% of initial position  (Multibagger milestone achieved!)",
        " 🏃 100%+ Gain ---> Hold remaining 20% as 'Free Runner' with 15% Trailing Stop Loss",
        "```",
        "",
        "---",
        "",
        "## Downside Protection & Stop Loss Rules",
        "",
        "1. **Hard Stop Loss (-12.0%):** If a stock drops 12.0% below average purchase cost, exit immediately to protect capital.",
        "2. **Trailing Stop Loss (15.0% from Peak):** Once a position gains +50%, activate a 15.0% trailing stop loss below its high watermark.",
        "3. **Fundamental Thesis Break Rules:** Exit position completely (regardless of price) if any of the following occur:",
        "   - Debt-to-Equity ratio rises above **0.50**.",
        "   - Sequential Net Income declines for **2 consecutive quarters**.",
        "   - Promoter stake drops by **> 3.0%** in a single quarter.",
        "   - Statutory auditor resigns or regulator issues adverse action.",
        "",
        "---",
        "",
        "## Individual Position Execution Detail",
        ""
    ])

    for _, r in df_plan.iterrows():
        lines.extend([
            f"### #{r['Rank']}: `{r['Ticker']}` — {r['Classification']}",
            f"- **Target Allocation:** **{r['Allocation %']:.2f}%** (₹{r['Position Size (INR)']:,.2f} out of ₹10L)",
            f"- **Buy Priority:** {r['Buy Priority']}",
            f"- **Risk Level:** {r['Risk Level']}",
            f"- **Suggested Holding Period:** {r['Suggested Holding Period']}",
            f"- **Thesis:** *\"{r['Investment Thesis']}\"*",
            f"- **Profit Booking Rule:** `{r['Slab-wise Profit Booking']}`",
            f"- **Exit Triggers:** `{r['Thesis Break Rules']}`",
            ""
        ])

    lines.extend([
        "---",
        "",
        "## Disclaimer",
        "*This portfolio execution plan is generated for educational and quantitative research purposes only. "
        "Position sizing and exit rules must be customized based on personal risk tolerance. Consult a SEBI-registered advisor.*"
    ])

    with open(OUTPUT_STRATEGY_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(f"Generated {OUTPUT_STRATEGY_MD.name}")
    return OUTPUT_STRATEGY_MD


# ------------------------------------------------------------------------------
# MAIN PIPELINE ORCHESTRATOR
# ------------------------------------------------------------------------------
def main():
    import argparse
    parser = argparse.ArgumentParser(description="Stage 5: Portfolio & Sell Strategy Engine")
    parser.add_argument(
        "--capital", "--portfolio-size",
        type=float,
        default=1000000.0,
        help="Total portfolio capital amount in INR (default: 1000000)",
    )
    args, _ = parser.parse_known_args()
    CONFIG["REFERENCE_PORTFOLIO_INR"] = args.capital

    logger.info("=" * 80)
    logger.info(f"STAGE 5: PORTFOLIO & SELL STRATEGY ENGINE STARTED (Capital: ₹{CONFIG['REFERENCE_PORTFOLIO_INR']:,.2f})")
    logger.info("=" * 80)

    # Step 1: Load Stage 4 Rankings
    df_rankings = load_stage4_rankings()

    # Step 2: Compute Portfolio Allocation Weights
    df_weighted = calculate_portfolio_weights(df_rankings)

    # Step 3: Generate Strategy for each position
    plan_rows = []
    for _, row in df_weighted.iterrows():
        strat = generate_position_strategy(row)
        plan_rows.append(strat)

    df_plan = pd.DataFrame(plan_rows)

    # Step 4: Export CSV: portfolio_plan.csv
    csv_cols = [
        "Rank", "Ticker", "Final Score", "Allocation %", "Position Size (INR)",
        "Buy Priority", "Risk Level", "Suggested Holding Period",
        "Slab-wise Profit Booking", "Stop Loss Rule", "Thesis Break Rules",
        "Investment Category", "Classification", "Investment Thesis"
    ]
    df_plan[csv_cols].to_csv(OUTPUT_PLAN_CSV, index=False)
    logger.info(f"Saved {OUTPUT_PLAN_CSV.name} ({len(df_plan)} rows).")

    # Step 5: Generate Markdown Report
    generate_portfolio_markdown_report(df_plan)

    # Step 6: Console Summary Output
    print("\n" + "=" * 140)
    print("STAGE 5: PORTFOLIO & SELL STRATEGY ENGINE — MASTER POSITION ALLOCATION PLAN")
    print("=" * 140)
    print(f"{'Rank':<5} | {'Ticker':<14} | {'Score':>6} | {'Alloc %':>8} | {'Pos Size (₹)':>14} | {'Buy Priority':<32} | {'Suggested Holding Period'}")
    print("-" * 140)
    for _, r in df_plan.iterrows():
        print(
            f"#{r['Rank']:<4} | {r['Ticker']:<14} | {r['Final Score']:>6.2f} | "
            f"{r['Allocation %']:>7.2f}% | ₹{r['Position Size (INR)']:>12,.2f} | "
            f"{r['Buy Priority']:<32} | {r['Suggested Holding Period']}"
        )
    print("=" * 140)

    print("\nSLAB-WISE PROFIT BOOKING & EXIT RULES SUMMARY:")
    for _, r in df_plan.iterrows():
        print(f"\n[{r['Ticker']} | Rank #{r['Rank']} | Alloc: {r['Allocation %']:.2f}% | Position: ₹{r['Position Size (INR)']:,.2f}]")
        print(f"  Priority     : {r['Buy Priority']}")
        print(f"  Profit Slabs : {r['Slab-wise Profit Booking']}")
        print(f"  Stop Loss    : {r['Stop Loss Rule']}")
        print(f"  Thesis Break : {r['Thesis Break Rules']}")

    logger.info("Stage 5 Portfolio & Sell Strategy Engine successfully completed.")


if __name__ == "__main__":
    main()
